//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    [DataContract]
    public partial class Alumno
    {
        [DataMember]
        public System.Guid Guid { get; set; }

        [DataMember]
        public string Nombre { get; set; }

        [DataMember]
        public string Apellidos { get; set; }

        [DataMember]
        public string Dni { get; set; }


        public Alumno() { }
        
    }
    
}
